package net.maisiemarlowe.angelsascent.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.maisiemarlowe.angelsascent.block.ModBlocks;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.util.Identifier;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider {
    public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup arg) {
        getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
                .add(ModBlocks.SOUL_ORE)
                .add(ModBlocks.HOLY_ORE)
                .add(ModBlocks.BLASPHEMOUS_ORE)

                .add(ModBlocks.CYAN_COBBLESTONE)
                .add(ModBlocks.BLUE_COBBLESTONE)
                .add(ModBlocks.BLACK_COBBLESTONE)
                .add(ModBlocks.BROWN_COBBLESTONE)
                .add(ModBlocks.GREEN_COBBLESTONE)
                .add(ModBlocks.GREY_COBBLESTONE)
                .add(ModBlocks.LIGHT_BLUE_COBBLESTONE)
                .add(ModBlocks.LIGHT_GREY_COBBLESTONE)
                .add(ModBlocks.ORANGE_COBBLESTONE)
                .add(ModBlocks.MAGENTA_COBBLESTONE)
                .add(ModBlocks.LIME_COBBLESTONE)
                .add(ModBlocks.WHITE_COBBLESTONE)
                .add(ModBlocks.YELLOW_COBBLESTONE)
                .add(ModBlocks.PURPLE_COBBLESTONE)
                .add(ModBlocks.RED_COBBLESTONE)
                .add(ModBlocks.PINK_COBBLESTONE)

                .add(ModBlocks.CYAN_STONE_BRICKS)
                .add(ModBlocks.BLUE_STONE_BRICKS)
                .add(ModBlocks.BLACK_STONE_BRICKS)
                .add(ModBlocks.BROWN_STONE_BRICKS)
                .add(ModBlocks.GREEN_STONE_BRICKS)
                .add(ModBlocks.GREY_STONE_BRICKS)
                .add(ModBlocks.LIGHT_BLUE_STONE_BRICKS)
                .add(ModBlocks.LIGHT_GREY_STONE_BRICKS)
                .add(ModBlocks.ORANGE_STONE_BRICKS)
                .add(ModBlocks.MAGENTA_STONE_BRICKS)
                .add(ModBlocks.LIME_STONE_BRICKS)
                .add(ModBlocks.WHITE_STONE_BRICKS)
                .add(ModBlocks.YELLOW_STONE_BRICKS)
                .add(ModBlocks.PURPLE_STONE_BRICKS)
                .add(ModBlocks.RED_STONE_BRICKS)
                .add(ModBlocks.PINK_STONE_BRICKS)

                .add(ModBlocks.CYAN_STONE)
                .add(ModBlocks.BLUE_STONE)
                .add(ModBlocks.BLACK_STONE)
                .add(ModBlocks.BROWN_STONE)
                .add(ModBlocks.GREEN_STONE)
                .add(ModBlocks.GREY_STONE)
                .add(ModBlocks.LIGHT_BLUE_STONE)
                .add(ModBlocks.LIGHT_GREY_STONE)
                .add(ModBlocks.ORANGE_STONE)
                .add(ModBlocks.MAGENTA_STONE)
                .add(ModBlocks.LIME_STONE)
                .add(ModBlocks.WHITE_STONE)
                .add(ModBlocks.YELLOW_STONE)
                .add(ModBlocks.PURPLE_STONE)
                .add(ModBlocks.RED_STONE)
                .add(ModBlocks.PINK_STONE)

                .add(ModBlocks.CYAN_SMOOTH_STONE)
                .add(ModBlocks.BLUE_SMOOTH_STONE)
                .add(ModBlocks.BLACK_SMOOTH_STONE)
                .add(ModBlocks.BROWN_SMOOTH_STONE)
                .add(ModBlocks.GREEN_SMOOTH_STONE)
                .add(ModBlocks.GREY_SMOOTH_STONE)
                .add(ModBlocks.LIGHT_BLUE_SMOOTH_STONE)
                .add(ModBlocks.LIGHT_GREY_SMOOTH_STONE)
                .add(ModBlocks.ORANGE_SMOOTH_STONE)
                .add(ModBlocks.MAGENTA_SMOOTH_STONE)
                .add(ModBlocks.LIME_SMOOTH_STONE)
                .add(ModBlocks.WHITE_SMOOTH_STONE)
                .add(ModBlocks.YELLOW_SMOOTH_STONE)
                .add(ModBlocks.PURPLE_SMOOTH_STONE)
                .add(ModBlocks.RED_SMOOTH_STONE)
                .add(ModBlocks.PINK_SMOOTH_STONE)

                .add(ModBlocks.CYAN_CRACKED_STONE_BRICKS)
                .add(ModBlocks.BLUE_CRACKED_STONE_BRICKS)
                .add(ModBlocks.BLACK_CRACKED_STONE_BRICKS)
                .add(ModBlocks.BROWN_CRACKED_STONE_BRICKS)
                .add(ModBlocks.GREEN_CRACKED_STONE_BRICKS)
                .add(ModBlocks.GREY_CRACKED_STONE_BRICKS)
                .add(ModBlocks.LIGHT_BLUE_CRACKED_STONE_BRICKS)
                .add(ModBlocks.LIGHT_GREY_CRACKED_STONE_BRICKS)
                .add(ModBlocks.ORANGE_CRACKED_STONE_BRICKS)
                .add(ModBlocks.MAGENTA_CRACKED_STONE_BRICKS)
                .add(ModBlocks.LIME_CRACKED_STONE_BRICKS)
                .add(ModBlocks.WHITE_CRACKED_STONE_BRICKS)
                .add(ModBlocks.YELLOW_CRACKED_STONE_BRICKS)
                .add(ModBlocks.PURPLE_CRACKED_STONE_BRICKS)
                .add(ModBlocks.RED_CRACKED_STONE_BRICKS)
                .add(ModBlocks.PINK_CRACKED_STONE_BRICKS)

                .add(ModBlocks.CYAN_CHISELED_STONE_BRICKS)
                .add(ModBlocks.BLUE_CHISELED_STONE_BRICKS)
                .add(ModBlocks.BLACK_CHISELED_STONE_BRICKS)
                .add(ModBlocks.BROWN_CHISELED_STONE_BRICKS)
                .add(ModBlocks.GREEN_CHISELED_STONE_BRICKS)
                .add(ModBlocks.GREY_CHISELED_STONE_BRICKS)
                .add(ModBlocks.LIGHT_BLUE_CHISELED_STONE_BRICKS)
                .add(ModBlocks.LIGHT_GREY_CHISELED_STONE_BRICKS)
                .add(ModBlocks.ORANGE_CHISELED_STONE_BRICKS)
                .add(ModBlocks.MAGENTA_CHISELED_STONE_BRICKS)
                .add(ModBlocks.LIME_CHISELED_STONE_BRICKS)
                .add(ModBlocks.WHITE_CHISELED_STONE_BRICKS)
                .add(ModBlocks.YELLOW_CHISELED_STONE_BRICKS)
                .add(ModBlocks.PURPLE_CHISELED_STONE_BRICKS)
                .add(ModBlocks.RED_CHISELED_STONE_BRICKS)
                .add(ModBlocks.PINK_CHISELED_STONE_BRICKS)

                .add(ModBlocks.CYAN_MOSSY_STONE_BRICKS)
                .add(ModBlocks.BLUE_MOSSY_STONE_BRICKS)
                .add(ModBlocks.BLACK_MOSSY_STONE_BRICKS)
                .add(ModBlocks.BROWN_MOSSY_STONE_BRICKS)
                .add(ModBlocks.GREEN_MOSSY_STONE_BRICKS)
                .add(ModBlocks.GREY_MOSSY_STONE_BRICKS)
                .add(ModBlocks.LIGHT_BLUE_MOSSY_STONE_BRICKS)
                .add(ModBlocks.LIGHT_GREY_MOSSY_STONE_BRICKS)
                .add(ModBlocks.ORANGE_MOSSY_STONE_BRICKS)
                .add(ModBlocks.MAGENTA_MOSSY_STONE_BRICKS)
                .add(ModBlocks.LIME_MOSSY_STONE_BRICKS)
                .add(ModBlocks.WHITE_MOSSY_STONE_BRICKS)
                .add(ModBlocks.YELLOW_MOSSY_STONE_BRICKS)
                .add(ModBlocks.PURPLE_MOSSY_STONE_BRICKS)
                .add(ModBlocks.RED_MOSSY_STONE_BRICKS)
                .add(ModBlocks.PINK_MOSSY_STONE_BRICKS)

                .add(ModBlocks.CYAN_STONE_STAIRS)
                .add(ModBlocks.BLUE_STONE_STAIRS)
                .add(ModBlocks.BLACK_STONE_STAIRS)
                .add(ModBlocks.BROWN_STONE_STAIRS)
                .add(ModBlocks.GREEN_STONE_STAIRS)
                .add(ModBlocks.GREY_STONE_STAIRS)
                .add(ModBlocks.LIGHT_BLUE_STONE_STAIRS)
                .add(ModBlocks.LIGHT_GREY_STONE_STAIRS)
                .add(ModBlocks.MAGENTA_STONE_STAIRS)
                .add(ModBlocks.LIME_STONE_STAIRS)
                .add(ModBlocks.WHITE_STONE_STAIRS)
                .add(ModBlocks.YELLOW_STONE_STAIRS)
                .add(ModBlocks.PURPLE_STONE_STAIRS)
                .add(ModBlocks.RED_STONE_STAIRS)
                .add(ModBlocks.PINK_STONE_STAIRS)

                .add(ModBlocks.CYAN_COBBLESTONE_STAIRS)
                .add(ModBlocks.BLUE_COBBLESTONE_STAIRS)
                .add(ModBlocks.BLACK_COBBLESTONE_STAIRS)
                .add(ModBlocks.BROWN_COBBLESTONE_STAIRS)
                .add(ModBlocks.GREEN_COBBLESTONE_STAIRS)
                .add(ModBlocks.GREY_COBBLESTONE_STAIRS)
                .add(ModBlocks.LIGHT_BLUE_COBBLESTONE_STAIRS)
                .add(ModBlocks.LIGHT_GREY_COBBLESTONE_STAIRS)
                .add(ModBlocks.MAGENTA_COBBLESTONE_STAIRS)
                .add(ModBlocks.LIME_COBBLESTONE_STAIRS)
                .add(ModBlocks.WHITE_COBBLESTONE_STAIRS)
                .add(ModBlocks.YELLOW_COBBLESTONE_STAIRS)
                .add(ModBlocks.PURPLE_COBBLESTONE_STAIRS)
                .add(ModBlocks.RED_COBBLESTONE_STAIRS)
                .add(ModBlocks.PINK_COBBLESTONE_STAIRS)

                .add(ModBlocks.CYAN_STONE_BRICK_STAIRS)
                .add(ModBlocks.BLUE_STONE_BRICK_STAIRS)
                .add(ModBlocks.BLACK_STONE_BRICK_STAIRS)
                .add(ModBlocks.BROWN_STONE_BRICK_STAIRS)
                .add(ModBlocks.GREEN_STONE_BRICK_STAIRS)
                .add(ModBlocks.GREY_STONE_BRICK_STAIRS)
                .add(ModBlocks.LIGHT_BLUE_STONE_BRICK_STAIRS)
                .add(ModBlocks.LIGHT_GREY_STONE_BRICK_STAIRS)
                .add(ModBlocks.MAGENTA_STONE_BRICK_STAIRS)
                .add(ModBlocks.LIME_STONE_BRICK_STAIRS)
                .add(ModBlocks.WHITE_STONE_BRICK_STAIRS)
                .add(ModBlocks.YELLOW_STONE_BRICK_STAIRS)
                .add(ModBlocks.PURPLE_STONE_BRICK_STAIRS)
                .add(ModBlocks.RED_STONE_BRICK_STAIRS)
                .add(ModBlocks.PINK_STONE_BRICK_STAIRS)

                .add(ModBlocks.CYAN_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.BLUE_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.BLACK_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.BROWN_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.GREEN_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.GREY_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.LIGHT_BLUE_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.LIGHT_GREY_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.MAGENTA_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.LIME_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.WHITE_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.YELLOW_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.PURPLE_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.RED_MOSSY_STONE_BRICK_STAIRS)
                .add(ModBlocks.PINK_MOSSY_STONE_BRICK_STAIRS)

                .add(ModBlocks.CYAN_STONE_SLAB)
                .add(ModBlocks.BLUE_STONE_SLAB)
                .add(ModBlocks.BLACK_STONE_SLAB)
                .add(ModBlocks.BROWN_STONE_SLAB)
                .add(ModBlocks.GREEN_STONE_SLAB)
                .add(ModBlocks.GREY_STONE_SLAB)
                .add(ModBlocks.LIGHT_BLUE_STONE_SLAB)
                .add(ModBlocks.LIGHT_GREY_STONE_SLAB)
                .add(ModBlocks.MAGENTA_STONE_SLAB)
                .add(ModBlocks.LIME_STONE_SLAB)
                .add(ModBlocks.WHITE_STONE_SLAB)
                .add(ModBlocks.YELLOW_STONE_SLAB)
                .add(ModBlocks.PURPLE_STONE_SLAB)
                .add(ModBlocks.RED_STONE_SLAB)
                .add(ModBlocks.PINK_STONE_SLAB)

                .add(ModBlocks.CYAN_COBBLESTONE_SLAB)
                .add(ModBlocks.BLUE_COBBLESTONE_SLAB)
                .add(ModBlocks.BLACK_COBBLESTONE_SLAB)
                .add(ModBlocks.BROWN_COBBLESTONE_SLAB)
                .add(ModBlocks.GREEN_COBBLESTONE_SLAB)
                .add(ModBlocks.GREY_COBBLESTONE_SLAB)
                .add(ModBlocks.LIGHT_BLUE_COBBLESTONE_SLAB)
                .add(ModBlocks.LIGHT_GREY_COBBLESTONE_SLAB)
                .add(ModBlocks.MAGENTA_COBBLESTONE_SLAB)
                .add(ModBlocks.LIME_COBBLESTONE_SLAB)
                .add(ModBlocks.WHITE_COBBLESTONE_SLAB)
                .add(ModBlocks.YELLOW_COBBLESTONE_SLAB)
                .add(ModBlocks.PURPLE_COBBLESTONE_SLAB)
                .add(ModBlocks.RED_COBBLESTONE_SLAB)
                .add(ModBlocks.PINK_COBBLESTONE_SLAB)

                .add(ModBlocks.CYAN_STONE_BRICK_SLAB)
                .add(ModBlocks.BLUE_STONE_BRICK_SLAB)
                .add(ModBlocks.BLACK_STONE_BRICK_SLAB)
                .add(ModBlocks.BROWN_STONE_BRICK_SLAB)
                .add(ModBlocks.GREEN_STONE_BRICK_SLAB)
                .add(ModBlocks.GREY_STONE_BRICK_SLAB)
                .add(ModBlocks.LIGHT_BLUE_STONE_BRICK_SLAB)
                .add(ModBlocks.LIGHT_GREY_STONE_BRICK_SLAB)
                .add(ModBlocks.MAGENTA_STONE_BRICK_SLAB)
                .add(ModBlocks.LIME_STONE_BRICK_SLAB)
                .add(ModBlocks.WHITE_STONE_BRICK_SLAB)
                .add(ModBlocks.YELLOW_STONE_BRICK_SLAB)
                .add(ModBlocks.PURPLE_STONE_BRICK_SLAB)
                .add(ModBlocks.RED_STONE_BRICK_SLAB)
                .add(ModBlocks.PINK_STONE_BRICK_SLAB)

                .add(ModBlocks.CYAN_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.BLUE_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.BLACK_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.BROWN_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.GREEN_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.GREY_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.LIGHT_BLUE_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.LIGHT_GREY_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.MAGENTA_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.LIME_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.WHITE_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.YELLOW_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.PURPLE_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.RED_MOSSY_STONE_BRICK_SLAB)
                .add(ModBlocks.PINK_MOSSY_STONE_BRICK_SLAB)

//                .add(ModBlocks.CYAN_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.BLUE_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.BLACK_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.BROWN_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.GREEN_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.GREY_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.LIGHT_BLUE_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.LIGHT_GREY_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.MAGENTA_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.LIME_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.WHITE_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.YELLOW_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.PURPLE_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.RED_SMOOTH_STONE_SLAB)
//                .add(ModBlocks.PINK_SMOOTH_STONE_SLAB)

                .add(ModBlocks.CYAN_STONE_BUTTON)
                .add(ModBlocks.BLUE_STONE_BUTTON)
                .add(ModBlocks.BLACK_STONE_BUTTON)
                .add(ModBlocks.BROWN_STONE_BUTTON)
                .add(ModBlocks.GREEN_STONE_BUTTON)
                .add(ModBlocks.GREY_STONE_BUTTON)
                .add(ModBlocks.LIGHT_BLUE_STONE_BUTTON)
                .add(ModBlocks.LIGHT_GREY_STONE_BUTTON)
                .add(ModBlocks.MAGENTA_STONE_BUTTON)
                .add(ModBlocks.LIME_STONE_BUTTON)
                .add(ModBlocks.WHITE_STONE_BUTTON)
                .add(ModBlocks.YELLOW_STONE_BUTTON)
                .add(ModBlocks.PURPLE_STONE_BUTTON)
                .add(ModBlocks.RED_STONE_BUTTON)
                .add(ModBlocks.PINK_STONE_BUTTON)

                .add(ModBlocks.CYAN_STONE_PRESSURE_PLATE)
                .add(ModBlocks.BLUE_STONE_PRESSURE_PLATE)
                .add(ModBlocks.BLACK_STONE_PRESSURE_PLATE)
                .add(ModBlocks.BROWN_STONE_PRESSURE_PLATE)
                .add(ModBlocks.GREEN_STONE_PRESSURE_PLATE)
                .add(ModBlocks.GREY_STONE_PRESSURE_PLATE)
                .add(ModBlocks.LIGHT_BLUE_STONE_PRESSURE_PLATE)
                .add(ModBlocks.LIGHT_GREY_STONE_PRESSURE_PLATE)
                .add(ModBlocks.MAGENTA_STONE_PRESSURE_PLATE)
                .add(ModBlocks.LIME_STONE_PRESSURE_PLATE)
                .add(ModBlocks.WHITE_STONE_PRESSURE_PLATE)
                .add(ModBlocks.YELLOW_STONE_PRESSURE_PLATE)
                .add(ModBlocks.PURPLE_STONE_PRESSURE_PLATE)
                .add(ModBlocks.RED_STONE_PRESSURE_PLATE)
                .add(ModBlocks.PINK_STONE_PRESSURE_PLATE)

                .add(ModBlocks.WHITE_STONE_BRICK_WALL)
                .add(ModBlocks.LIGHT_GREY_STONE_BRICK_WALL)
                .add(ModBlocks.GREY_STONE_BRICK_WALL)
                .add(ModBlocks.BLACK_STONE_BRICK_WALL)
                .add(ModBlocks.BROWN_STONE_BRICK_WALL)
                .add(ModBlocks.RED_STONE_BRICK_WALL)
                .add(ModBlocks.ORANGE_STONE_BRICK_WALL)
                .add(ModBlocks.YELLOW_STONE_BRICK_WALL)
                .add(ModBlocks.LIME_STONE_BRICK_WALL)
                .add(ModBlocks.GREEN_STONE_BRICK_WALL)
                .add(ModBlocks.CYAN_STONE_BRICK_WALL)
                .add(ModBlocks.LIGHT_BLUE_STONE_BRICK_WALL)
                .add(ModBlocks.BLUE_STONE_BRICK_WALL)
                .add(ModBlocks.PURPLE_STONE_BRICK_WALL)
                .add(ModBlocks.MAGENTA_STONE_BRICK_WALL)
                .add(ModBlocks.PINK_STONE_BRICK_WALL)

                .add(ModBlocks.CYAN_COBBLESTONE_WALL)
                .add(ModBlocks.BLUE_COBBLESTONE_WALL)
                .add(ModBlocks.BLACK_COBBLESTONE_WALL)
                .add(ModBlocks.BROWN_COBBLESTONE_WALL)
                .add(ModBlocks.GREEN_COBBLESTONE_WALL)
                .add(ModBlocks.GREY_COBBLESTONE_WALL)
                .add(ModBlocks.LIGHT_BLUE_COBBLESTONE_WALL)
                .add(ModBlocks.LIGHT_GREY_COBBLESTONE_WALL)
                .add(ModBlocks.MAGENTA_COBBLESTONE_WALL)
                .add(ModBlocks.LIME_COBBLESTONE_WALL)
                .add(ModBlocks.WHITE_COBBLESTONE_WALL)
                .add(ModBlocks.YELLOW_COBBLESTONE_WALL)
                .add(ModBlocks.PURPLE_COBBLESTONE_WALL)
                .add(ModBlocks.RED_COBBLESTONE_WALL)
                .add(ModBlocks.PINK_COBBLESTONE_WALL)



        ;

        getOrCreateTagBuilder(BlockTags.WALLS)

                .add(ModBlocks.WHITE_STONE_BRICK_WALL)
                .add(ModBlocks.LIGHT_GREY_STONE_BRICK_WALL)
                .add(ModBlocks.GREY_STONE_BRICK_WALL)
                .add(ModBlocks.BLACK_STONE_BRICK_WALL)
                .add(ModBlocks.BROWN_STONE_BRICK_WALL)
                .add(ModBlocks.RED_STONE_BRICK_WALL)
                .add(ModBlocks.ORANGE_STONE_BRICK_WALL)
                .add(ModBlocks.YELLOW_STONE_BRICK_WALL)
                .add(ModBlocks.LIME_STONE_BRICK_WALL)
                .add(ModBlocks.GREEN_STONE_BRICK_WALL)
                .add(ModBlocks.CYAN_STONE_BRICK_WALL)
                .add(ModBlocks.LIGHT_BLUE_STONE_BRICK_WALL)
                .add(ModBlocks.BLUE_STONE_BRICK_WALL)
                .add(ModBlocks.PURPLE_STONE_BRICK_WALL)
                .add(ModBlocks.MAGENTA_STONE_BRICK_WALL)
                .add(ModBlocks.PINK_STONE_BRICK_WALL)

                .add(ModBlocks.CYAN_COBBLESTONE_WALL)
                .add(ModBlocks.BLUE_COBBLESTONE_WALL)
                .add(ModBlocks.BLACK_COBBLESTONE_WALL)
                .add(ModBlocks.BROWN_COBBLESTONE_WALL)
                .add(ModBlocks.GREEN_COBBLESTONE_WALL)
                .add(ModBlocks.GREY_COBBLESTONE_WALL)
                .add(ModBlocks.LIGHT_BLUE_COBBLESTONE_WALL)
                .add(ModBlocks.LIGHT_GREY_COBBLESTONE_WALL)
                .add(ModBlocks.MAGENTA_COBBLESTONE_WALL)
                .add(ModBlocks.LIME_COBBLESTONE_WALL)
                .add(ModBlocks.WHITE_COBBLESTONE_WALL)
                .add(ModBlocks.YELLOW_COBBLESTONE_WALL)
                .add(ModBlocks.PURPLE_COBBLESTONE_WALL)
                .add(ModBlocks.RED_COBBLESTONE_WALL)
                .add(ModBlocks.PINK_COBBLESTONE_WALL)

                .add(ModBlocks.WHITE_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.LIGHT_GREY_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.GREY_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.BLACK_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.BROWN_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.RED_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.ORANGE_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.YELLOW_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.LIME_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.GREEN_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.CYAN_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.LIGHT_BLUE_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.BLUE_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.PURPLE_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.MAGENTA_MOSSY_STONE_BRICK_WALL)
                .add(ModBlocks.PINK_MOSSY_STONE_BRICK_WALL)



        ;

        getOrCreateTagBuilder(BlockTags.AXE_MINEABLE)

        ;

        getOrCreateTagBuilder(BlockTags.SHOVEL_MINEABLE)

        ;

        getOrCreateTagBuilder(BlockTags.HOE_MINEABLE)

        ;

        getOrCreateTagBuilder(BlockTags.NEEDS_STONE_TOOL)

        ;

        getOrCreateTagBuilder(BlockTags.NEEDS_IRON_TOOL)

        ;

        getOrCreateTagBuilder(BlockTags.NEEDS_DIAMOND_TOOL)

        ;

        getOrCreateTagBuilder(TagKey.of(RegistryKeys.BLOCK, new Identifier("fabric", "needs_tool_level_4")))
                .add(ModBlocks.SOUL_ORE)
        ;

        getOrCreateTagBuilder(TagKey.of(RegistryKeys.BLOCK, new Identifier("fabric", "needs_tool_level_5")))
                .add(ModBlocks.HOLY_ORE)
        ;

        getOrCreateTagBuilder(TagKey.of(RegistryKeys.BLOCK, new Identifier("fabric", "needs_tool_level_6")))
                .add(ModBlocks.BLASPHEMOUS_ORE)
        ;

    }
}
